package robotoer.util;

import org.antlr.v4.runtime.ParserRuleContext;
import org.antlr.v4.runtime.tree.ErrorNode;
import org.antlr.v4.runtime.tree.TerminalNode;
import robotoer.ast.java.JavaParser;

public interface SimpleJavaVisitor<T> {
  T visit(final JavaParser.InnerCreatorContext nodeContext);
  T visit(final JavaParser.GenericMethodDeclarationContext nodeContext);
  T visit(final JavaParser.ExpressionListContext nodeContext);
  T visit(final JavaParser.TypeDeclarationContext nodeContext);
  T visit(final JavaParser.ForUpdateContext nodeContext);
  T visit(final JavaParser.AnnotationContext nodeContext);
  T visit(final JavaParser.EnumConstantContext nodeContext);
  T visit(final JavaParser.ImportDeclarationContext nodeContext);
  T visit(final JavaParser.AnnotationMethodOrConstantRestContext nodeContext);
  T visit(final JavaParser.EnumConstantNameContext nodeContext);
  T visit(final JavaParser.FinallyBlockContext nodeContext);
  T visit(final JavaParser.VariableDeclaratorsContext nodeContext);
  T visit(final JavaParser.ElementValuePairsContext nodeContext);
  T visit(final JavaParser.InterfaceMethodDeclarationContext nodeContext);
  T visit(final JavaParser.InterfaceBodyDeclarationContext nodeContext);
  T visit(final JavaParser.EnumConstantsContext nodeContext);
  T visit(final JavaParser.CatchClauseContext nodeContext);
  T visit(final JavaParser.ConstantExpressionContext nodeContext);
  T visit(final JavaParser.EnumDeclarationContext nodeContext);
  T visit(final JavaParser.ExplicitGenericInvocationSuffixContext nodeContext);
  T visit(final JavaParser.TypeParameterContext nodeContext);
  T visit(final JavaParser.EnumBodyDeclarationsContext nodeContext);
  T visit(final JavaParser.TypeBoundContext nodeContext);
  T visit(final JavaParser.StatementExpressionContext nodeContext);
  T visit(final JavaParser.VariableInitializerContext nodeContext);
  T visit(final JavaParser.BlockContext nodeContext);
  T visit(final JavaParser.GenericInterfaceMethodDeclarationContext nodeContext);
  T visit(final JavaParser.LocalVariableDeclarationStatementContext nodeContext);
  T visit(final JavaParser.SuperSuffixContext nodeContext);
  T visit(final JavaParser.FieldDeclarationContext nodeContext);
  T visit(final JavaParser.FormalParameterListContext nodeContext);
  T visit(final JavaParser.ExplicitGenericInvocationContext nodeContext);
  T visit(final JavaParser.ParExpressionContext nodeContext);
  T visit(final JavaParser.SwitchLabelContext nodeContext);
  T visit(final JavaParser.TypeParametersContext nodeContext);
  T visit(final JavaParser.QualifiedNameContext nodeContext);
  T visit(final JavaParser.ClassDeclarationContext nodeContext);
  T visit(final JavaParser.AnnotationConstantRestContext nodeContext);
  T visit(final JavaParser.ArgumentsContext nodeContext);
  T visit(final JavaParser.ConstructorBodyContext nodeContext);
  T visit(final JavaParser.FormalParametersContext nodeContext);
  T visit(final JavaParser.TypeArgumentContext nodeContext);
  T visit(final JavaParser.ForInitContext nodeContext);
  T visit(final JavaParser.VariableDeclaratorContext nodeContext);
  T visit(final JavaParser.AnnotationTypeDeclarationContext nodeContext);
  T visit(final JavaParser.ExpressionContext nodeContext);
  T visit(final JavaParser.ResourcesContext nodeContext);
  T visit(final JavaParser.FormalParameterContext nodeContext);
  T visit(final JavaParser.TypeContext nodeContext);
  T visit(final JavaParser.ElementValueArrayInitializerContext nodeContext);
  T visit(final JavaParser.AnnotationNameContext nodeContext);
  T visit(final JavaParser.EnhancedForControlContext nodeContext);
  T visit(final JavaParser.AnnotationMethodRestContext nodeContext);
  T visit(final JavaParser.PrimaryContext nodeContext);
  T visit(final JavaParser.ClassBodyContext nodeContext);
  T visit(final JavaParser.ClassOrInterfaceModifierContext nodeContext);
  T visit(final JavaParser.DefaultValueContext nodeContext);
  T visit(final JavaParser.VariableModifierContext nodeContext);
  T visit(final JavaParser.ConstDeclarationContext nodeContext);
  T visit(final JavaParser.CreatedNameContext nodeContext);
  T visit(final JavaParser.InterfaceDeclarationContext nodeContext);
  T visit(final JavaParser.PackageDeclarationContext nodeContext);
  T visit(final JavaParser.ConstantDeclaratorContext nodeContext);
  T visit(final JavaParser.CatchTypeContext nodeContext);
  T visit(final JavaParser.TypeArgumentsContext nodeContext);
  T visit(final JavaParser.ClassCreatorRestContext nodeContext);
  T visit(final JavaParser.ModifierContext nodeContext);
  T visit(final JavaParser.StatementContext nodeContext);
  T visit(final JavaParser.InterfaceBodyContext nodeContext);
  T visit(final JavaParser.ClassBodyDeclarationContext nodeContext);
  T visit(final JavaParser.LastFormalParameterContext nodeContext);
  T visit(final JavaParser.ForControlContext nodeContext);
  T visit(final JavaParser.TypeListContext nodeContext);
  T visit(final JavaParser.LocalVariableDeclarationContext nodeContext);
  T visit(final JavaParser.VariableDeclaratorIdContext nodeContext);
  T visit(final JavaParser.CompilationUnitContext nodeContext);
  T visit(final JavaParser.ElementValueContext nodeContext);
  T visit(final JavaParser.ClassOrInterfaceTypeContext nodeContext);
  T visit(final JavaParser.TypeArgumentsOrDiamondContext nodeContext);
  T visit(final JavaParser.AnnotationTypeElementDeclarationContext nodeContext);
  T visit(final JavaParser.BlockStatementContext nodeContext);
  T visit(final JavaParser.AnnotationTypeBodyContext nodeContext);
  T visit(final JavaParser.QualifiedNameListContext nodeContext);
  T visit(final JavaParser.CreatorContext nodeContext);
  T visit(final JavaParser.MemberDeclarationContext nodeContext);
  T visit(final JavaParser.MethodDeclarationContext nodeContext);
  T visit(final JavaParser.AnnotationTypeElementRestContext nodeContext);
  T visit(final JavaParser.ResourceSpecificationContext nodeContext);
  T visit(final JavaParser.ConstructorDeclarationContext nodeContext);
  T visit(final JavaParser.ResourceContext nodeContext);
  T visit(final JavaParser.ElementValuePairContext nodeContext);
  T visit(final JavaParser.MethodBodyContext nodeContext);
  T visit(final JavaParser.ArrayInitializerContext nodeContext);
  T visit(final JavaParser.NonWildcardTypeArgumentsOrDiamondContext nodeContext);
  T visit(final JavaParser.PrimitiveTypeContext nodeContext);
  T visit(final JavaParser.NonWildcardTypeArgumentsContext nodeContext);
  T visit(final JavaParser.ArrayCreatorRestContext nodeContext);
  T visit(final JavaParser.InterfaceMemberDeclarationContext nodeContext);
  T visit(final JavaParser.GenericConstructorDeclarationContext nodeContext);
  T visit(final JavaParser.LiteralContext nodeContext);
  T visit(final JavaParser.SwitchBlockStatementGroupContext nodeContext);

  // Genery node?
  T visit(final ParserRuleContext nodeContext);

  // Gener
  T visit(final TerminalNode node);
  T visit(final ErrorNode node);
}
