package robotoer.util;

import org.antlr.v4.runtime.ParserRuleContext;
import org.antlr.v4.runtime.tree.ErrorNode;
import org.antlr.v4.runtime.tree.TerminalNode;
import robotoer.ast.java.JavaParser;

public interface SimpleJavaVisitor<T, C> {
  T visit(final C context, final JavaParser.InnerCreatorContext nodeContext);
  T visit(final C context, final JavaParser.GenericMethodDeclarationContext nodeContext);
  T visit(final C context, final JavaParser.ExpressionListContext nodeContext);
  T visit(final C context, final JavaParser.TypeDeclarationContext nodeContext);
  T visit(final C context, final JavaParser.ForUpdateContext nodeContext);
  T visit(final C context, final JavaParser.AnnotationContext nodeContext);
  T visit(final C context, final JavaParser.EnumConstantContext nodeContext);
  T visit(final C context, final JavaParser.ImportDeclarationContext nodeContext);
  T visit(final C context, final JavaParser.AnnotationMethodOrConstantRestContext nodeContext);
  T visit(final C context, final JavaParser.EnumConstantNameContext nodeContext);
  T visit(final C context, final JavaParser.FinallyBlockContext nodeContext);
  T visit(final C context, final JavaParser.VariableDeclaratorsContext nodeContext);
  T visit(final C context, final JavaParser.ElementValuePairsContext nodeContext);
  T visit(final C context, final JavaParser.InterfaceMethodDeclarationContext nodeContext);
  T visit(final C context, final JavaParser.InterfaceBodyDeclarationContext nodeContext);
  T visit(final C context, final JavaParser.EnumConstantsContext nodeContext);
  T visit(final C context, final JavaParser.CatchClauseContext nodeContext);
  T visit(final C context, final JavaParser.ConstantExpressionContext nodeContext);
  T visit(final C context, final JavaParser.EnumDeclarationContext nodeContext);
  T visit(final C context, final JavaParser.ExplicitGenericInvocationSuffixContext nodeContext);
  T visit(final C context, final JavaParser.TypeParameterContext nodeContext);
  T visit(final C context, final JavaParser.EnumBodyDeclarationsContext nodeContext);
  T visit(final C context, final JavaParser.TypeBoundContext nodeContext);
  T visit(final C context, final JavaParser.StatementExpressionContext nodeContext);
  T visit(final C context, final JavaParser.VariableInitializerContext nodeContext);
  T visit(final C context, final JavaParser.BlockContext nodeContext);
  T visit(final C context, final JavaParser.GenericInterfaceMethodDeclarationContext nodeContext);
  T visit(final C context, final JavaParser.LocalVariableDeclarationStatementContext nodeContext);
  T visit(final C context, final JavaParser.SuperSuffixContext nodeContext);
  T visit(final C context, final JavaParser.FieldDeclarationContext nodeContext);
  T visit(final C context, final JavaParser.FormalParameterListContext nodeContext);
  T visit(final C context, final JavaParser.ExplicitGenericInvocationContext nodeContext);
  T visit(final C context, final JavaParser.ParExpressionContext nodeContext);
  T visit(final C context, final JavaParser.SwitchLabelContext nodeContext);
  T visit(final C context, final JavaParser.TypeParametersContext nodeContext);
  T visit(final C context, final JavaParser.QualifiedNameContext nodeContext);
  T visit(final C context, final JavaParser.ClassDeclarationContext nodeContext);
  T visit(final C context, final JavaParser.AnnotationConstantRestContext nodeContext);
  T visit(final C context, final JavaParser.ArgumentsContext nodeContext);
  T visit(final C context, final JavaParser.ConstructorBodyContext nodeContext);
  T visit(final C context, final JavaParser.FormalParametersContext nodeContext);
  T visit(final C context, final JavaParser.TypeArgumentContext nodeContext);
  T visit(final C context, final JavaParser.ForInitContext nodeContext);
  T visit(final C context, final JavaParser.VariableDeclaratorContext nodeContext);
  T visit(final C context, final JavaParser.AnnotationTypeDeclarationContext nodeContext);
  T visit(final C context, final JavaParser.ExpressionContext nodeContext);
  T visit(final C context, final JavaParser.ResourcesContext nodeContext);
  T visit(final C context, final JavaParser.FormalParameterContext nodeContext);
  T visit(final C context, final JavaParser.TypeContext nodeContext);
  T visit(final C context, final JavaParser.ElementValueArrayInitializerContext nodeContext);
  T visit(final C context, final JavaParser.AnnotationNameContext nodeContext);
  T visit(final C context, final JavaParser.EnhancedForControlContext nodeContext);
  T visit(final C context, final JavaParser.AnnotationMethodRestContext nodeContext);
  T visit(final C context, final JavaParser.PrimaryContext nodeContext);
  T visit(final C context, final JavaParser.ClassBodyContext nodeContext);
  T visit(final C context, final JavaParser.ClassOrInterfaceModifierContext nodeContext);
  T visit(final C context, final JavaParser.DefaultValueContext nodeContext);
  T visit(final C context, final JavaParser.VariableModifierContext nodeContext);
  T visit(final C context, final JavaParser.ConstDeclarationContext nodeContext);
  T visit(final C context, final JavaParser.CreatedNameContext nodeContext);
  T visit(final C context, final JavaParser.InterfaceDeclarationContext nodeContext);
  T visit(final C context, final JavaParser.PackageDeclarationContext nodeContext);
  T visit(final C context, final JavaParser.ConstantDeclaratorContext nodeContext);
  T visit(final C context, final JavaParser.CatchTypeContext nodeContext);
  T visit(final C context, final JavaParser.TypeArgumentsContext nodeContext);
  T visit(final C context, final JavaParser.ClassCreatorRestContext nodeContext);
  T visit(final C context, final JavaParser.ModifierContext nodeContext);
  T visit(final C context, final JavaParser.StatementContext nodeContext);
  T visit(final C context, final JavaParser.InterfaceBodyContext nodeContext);
  T visit(final C context, final JavaParser.ClassBodyDeclarationContext nodeContext);
  T visit(final C context, final JavaParser.LastFormalParameterContext nodeContext);
  T visit(final C context, final JavaParser.ForControlContext nodeContext);
  T visit(final C context, final JavaParser.TypeListContext nodeContext);
  T visit(final C context, final JavaParser.LocalVariableDeclarationContext nodeContext);
  T visit(final C context, final JavaParser.VariableDeclaratorIdContext nodeContext);
  T visit(final C context, final JavaParser.CompilationUnitContext nodeContext);
  T visit(final C context, final JavaParser.ElementValueContext nodeContext);
  T visit(final C context, final JavaParser.ClassOrInterfaceTypeContext nodeContext);
  T visit(final C context, final JavaParser.TypeArgumentsOrDiamondContext nodeContext);
  T visit(final C context, final JavaParser.AnnotationTypeElementDeclarationContext nodeContext);
  T visit(final C context, final JavaParser.BlockStatementContext nodeContext);
  T visit(final C context, final JavaParser.AnnotationTypeBodyContext nodeContext);
  T visit(final C context, final JavaParser.QualifiedNameListContext nodeContext);
  T visit(final C context, final JavaParser.CreatorContext nodeContext);
  T visit(final C context, final JavaParser.MemberDeclarationContext nodeContext);
  T visit(final C context, final JavaParser.MethodDeclarationContext nodeContext);
  T visit(final C context, final JavaParser.AnnotationTypeElementRestContext nodeContext);
  T visit(final C context, final JavaParser.ResourceSpecificationContext nodeContext);
  T visit(final C context, final JavaParser.ConstructorDeclarationContext nodeContext);
  T visit(final C context, final JavaParser.ResourceContext nodeContext);
  T visit(final C context, final JavaParser.ElementValuePairContext nodeContext);
  T visit(final C context, final JavaParser.MethodBodyContext nodeContext);
  T visit(final C context, final JavaParser.ArrayInitializerContext nodeContext);
  T visit(final C context, final JavaParser.NonWildcardTypeArgumentsOrDiamondContext nodeContext);
  T visit(final C context, final JavaParser.PrimitiveTypeContext nodeContext);
  T visit(final C context, final JavaParser.NonWildcardTypeArgumentsContext nodeContext);
  T visit(final C context, final JavaParser.ArrayCreatorRestContext nodeContext);
  T visit(final C context, final JavaParser.InterfaceMemberDeclarationContext nodeContext);
  T visit(final C context, final JavaParser.GenericConstructorDeclarationContext nodeContext);
  T visit(final C context, final JavaParser.LiteralContext nodeContext);
  T visit(final C context, final JavaParser.SwitchBlockStatementGroupContext nodeContext);

  // Generic visitor for any node?
  T visit(final C context, final ParserRuleContext nodeContext);

  // Generic visitor for
  T visit(final C context, final TerminalNode node);
  T visit(final C context, final ErrorNode node);
}
